In [1]:
import pandas as pd
import numpy as np
from joblib import dump
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, ExtraTreesRegressor ,AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

In [2]:
df = pd.read_csv("Data.csv")
df.head()

,Date,OIL,GOLD,USDIDR,SP500,IHSG,VIX,CPI,BI_rate,US_rate
0,2010-01-01,NaN,NaN,9385.599609,NaN,NaN,NaN,5.134206,6.5,0.11
1,2010-01-04,81.510002,1117.699951,9364.200195,1132.989990,2575.312988,20.040001,5.134206,6.5,0.11
2,2010-01-05,81.769997,1118.099976,9305.200195,1136.520020,2605.175537,19.350000,5.134206,6.5,0.11
3,2010-01-06,83.180000,1135.900024,9218.099609,1137.140015,2603.195557,19.160000,5.134206,6.5,0.11
4,2010-01-07,82.660004,1133.099976,9272.500000,1141.689941,2586.794189,19.059999,5.134206,6.5,0.11

In [3]:
def years(date):
    year = str(date)
    yer = year[0:4]
    return int(yer)

# df["Date"].str.replace("-","")
df["year"] = df["Date"].apply(years)

df.drop("Date",axis=1,inplace=True)

df.head()

,OIL,GOLD,USDIDR,SP500,IHSG,VIX,CPI,BI_rate,US_rate,year
0,NaN,NaN,9385.599609,NaN,NaN,NaN,5.134206,6.5,0.11,2010
1,81.510002,1117.699951,9364.200195,1132.989990,2575.312988,20.040001,5.134206,6.5,0.11,2010
2,81.769997,1118.099976,9305.200195,1136.520020,2605.175537,19.350000,5.134206,6.5,0.11,2010
3,83.180000,1135.900024,9218.099609,1137.140015,2603.195557,19.160000,5.134206,6.5,0.11,2010
4,82.660004,1133.099976,9272.500000,1141.689941,2586.794189,19.059999,5.134206,6.5,0.11,2010

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   OIL      4276 non-null   float64
 1   GOLD     4276 non-null   float64
 2   USDIDR   4277 non-null   float64
 3   SP500    4276 non-null   float64
 4   IHSG     4276 non-null   float64
 5   VIX      4276 non-null   float64
 6   CPI      4277 non-null   float64
 7   BI_rate  4277 non-null   float64
 8   US_rate  4277 non-null   float64
 9   year     4277 non-null   int64
dtypes: float64(9), int64(1)
memory usage: 334.3 KB

In [5]:
df.describe()

,OIL,GOLD,USDIDR,SP500,IHSG,VIX,CPI,BI_rate,US_rate,year
count,4276.000000,4276.000000,4277.000000,4276.000000,4276.000000,4276.000000,4277.000000,4277.000000,4277.000000,4277.000000
mean,71.823964,1739.590551,13150.969966,3044.336779,5580.338877,18.413835,3.855963,5.631810,1.469932,2017.706804
std,20.797806,753.225443,2480.184935,1599.415934,1331.392063,6.786782,1.676885,1.215341,1.819801,4.738294
min,-37.630001,1050.800049,888.109985,1022.580017,2475.475586,9.140000,0.760000,3.500000,0.050000,2010.000000
25%,55.162498,1271.900024,11552.000000,1838.682465,4567.085938,13.790000,3.030585,4.750000,0.100000,2014.000000
50%,71.730000,1536.300049,13805.000000,2646.135010,5724.189209,16.740000,3.669387,5.750000,0.360000,2018.000000
75%,88.772501,1853.299957,14855.000000,4154.945068,6653.029175,21.072500,5.134206,6.500000,2.400000,2022.000000
max,123.699997,5318.399902,17840.000000,7580.060059,9134.700195,82.690002,6.412495,7.750000,5.330000,2026.000000

In [6]:
df.columns

Index(['OIL', 'GOLD', 'USDIDR', 'SP500', 'IHSG', 'VIX', 'CPI', 'BI_rate',
       'US_rate', 'year'],
      dtype='object')

In [7]:
df.shape

(4277, 10)

In [8]:
df.dropna(axis=0,inplace=True)
df.head()

,OIL,GOLD,USDIDR,SP500,IHSG,VIX,CPI,BI_rate,US_rate,year
1,81.510002,1117.699951,9364.200195,1132.989990,2575.312988,20.040001,5.134206,6.5,0.11,2010
2,81.769997,1118.099976,9305.200195,1136.520020,2605.175537,19.350000,5.134206,6.5,0.11,2010
3,83.180000,1135.900024,9218.099609,1137.140015,2603.195557,19.160000,5.134206,6.5,0.11,2010
4,82.660004,1133.099976,9272.500000,1141.689941,2586.794189,19.059999,5.134206,6.5,0.11,2010
5,82.750000,1138.199951,9212.700195,1144.979980,2614.268311,18.129999,5.134206,6.5,0.11,2010

In [9]:
df.isnull().sum()

OIL        0
GOLD       0
USDIDR     0
SP500      0
IHSG       0
VIX        0
CPI        0
BI_rate    0
US_rate    0
year       0
dtype: int64

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.shape

(4274, 10)

In [13]:
df.head()

,OIL,GOLD,USDIDR,SP500,IHSG,VIX,CPI,BI_rate,US_rate,year
1,81.510002,1117.699951,9364.200195,1132.989990,2575.312988,20.040001,5.134206,6.5,0.11,2010
2,81.769997,1118.099976,9305.200195,1136.520020,2605.175537,19.350000,5.134206,6.5,0.11,2010
3,83.180000,1135.900024,9218.099609,1137.140015,2603.195557,19.160000,5.134206,6.5,0.11,2010
4,82.660004,1133.099976,9272.500000,1141.689941,2586.794189,19.059999,5.134206,6.5,0.11,2010
5,82.750000,1138.199951,9212.700195,1144.979980,2614.268311,18.129999,5.134206,6.5,0.11,2010

In [14]:
col = df.drop(["IHSG","year"],axis=1).columns

scaler = StandardScaler()
df[col] = scaler.fit_transform(df[col])

df.head()

,OIL,GOLD,USDIDR,SP500,IHSG,VIX,CPI,BI_rate,US_rate,year
1,0.465592,-0.825615,-1.527103,-1.194960,2575.312988,0.240210,0.762101,0.714559,-0.747157,2010
2,0.478095,-0.825084,-1.550896,-1.192752,2605.175537,0.138466,0.762101,0.714559,-0.747157,2010
3,0.545901,-0.801453,-1.586022,-1.192364,2603.195557,0.110449,0.762101,0.714559,-0.747157,2010
4,0.520895,-0.805170,-1.564084,-1.189519,2586.794189,0.095703,0.762101,0.714559,-0.747157,2010
5,0.525222,-0.798400,-1.588200,-1.187462,2614.268311,-0.041431,0.762101,0.714559,-0.747157,2010

In [15]:
X = df.drop('IHSG',axis=1)
y = df["IHSG"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [16]:
results = []
models = {
    'Linear Regression': LinearRegression(),
    'Ridge Regression': Ridge(alpha=1.0),
    'Lasso Regression': Lasso(alpha=0.1, max_iter=10000),
    'ElasticNet': ElasticNet(alpha=0.1, l1_ratio=0.5),
    'Decision Tree': DecisionTreeRegressor(random_state=42),
    'Random Forest': RandomForestRegressor(random_state=42, n_jobs=-1),
    'Extra Trees': ExtraTreesRegressor(random_state=42, n_jobs=-1),
    'Gradient Boosting': GradientBoostingRegressor(random_state=42),
    'K-Neighbors': KNeighborsRegressor(),
    'Support Vector Regressor': SVR(kernel='rbf'),
    "XGBoost": XGBRegressor(random_state=42),
    "AdaBoost": AdaBoostRegressor(random_state=42),
}

In [17]:
for name,model in models.items():
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    R2_score = r2_score(y_test,y_pred)
    MSE = mean_squared_error(y_test, y_pred)
    MAE = mean_absolute_error(y_test, y_pred)
    RMSE = np.sqrt(MSE)
    results.append({
        "Name":name,
        "R2_score":R2_score,
        "MSE":MSE,
        "MAE":MAE,
        "RMSE":RMSE
    })

results_df = pd.DataFrame(results)
results_df

                        Name  R2_score           MSE          MAE         RMSE
0          Linear Regression  0.916170  1.621043e+05   314.516449   402.621828
1           Ridge Regression  0.916178  1.620901e+05   314.494216   402.604119
2           Lasso Regression  0.916198  1.620510e+05   314.455601   402.555530
3                 ElasticNet  0.916053  1.623321e+05   314.411821   402.904641
4              Decision Tree  0.993063  1.341468e+04    66.301377   115.821743
5              Random Forest  0.996491  6.785384e+03    50.724354    82.373445
6                Extra Trees  0.997667  4.511630e+03    42.593897    67.168666
7          Gradient Boosting  0.988472  2.229277e+04   110.180996   149.307623
8                K-Neighbors  0.993617  1.234268e+04    68.790566   111.097636
9   Support Vector Regressor -0.023504  1.979187e+06  1188.730148  1406.835756
10                   XGBoost  0.996126  7.491056e+03    58.154014    86.550889
11                  AdaBoost  0.963039  7.147367e+04   218.113822   267.345601

In [18]:
model_final = GradientBoostingRegressor(random_state=42)
model_final.fit(X_train,y_train)
y_pred = model_final.predict(X_test)
r2_score(y_test,y_pred)

0.9884716669002301

In [19]:
X.columns.tolist()

['OIL', 'GOLD', 'USDIDR', 'SP500', 'VIX', 'CPI', 'BI_rate', 'US_rate', 'year']

In [20]:
dump(model_final,"model1.pkl")
dump(scaler,"scaler.pkl")
dump(X.columns.tolist(),"columns.pkl")

['columns.pkl']

In [21]:
import numpy as np
import pandas as pd
import joblib

print("--- ML Components Loading Test ---")
try:
    # 1. Artifacts ko load karna
    model = joblib.load('model1.pkl')
    scaler = joblib.load('scaler.pkl')
    columns = joblib.load('columns.pkl')
    print("✅ Success: Saari `.pkl` files perfectly load ho gayi hain!")
    print(f"Trained Columns List: {columns}\n")
    
    # 2. Test Input Data (Aap isme values badal kar check kar sakte hain)
    # Order: OIL, GOLD, USDIDR, SP500, VIX, CPI, BI_rate, US_rate
    test_year = 2026
    test_continuous_inputs = [[75.30, 1100.30, 9302.00, 1100.00, 20.00, 5.13, 6.50, 0.11]]
    
    print("--- Pipeline Execution Test ---")
    # 3. Continuous features ko scale karna (8 features)
    features_scaled = scaler.transform(test_continuous_inputs)
    
    # 4. Year ko aakhiri me stack karna (Jaise training me tha)
    year_input = np.array([[int(test_year)]])
    final_model_input = np.hstack((features_scaled, year_input))
    
    # 5. DataFrame banana training columns ke sath
    feature_names = ['OIL', 'GOLD', 'USDIDR', 'SP500', 'VIX', 'CPI', 'BI_rate', 'US_rate', 'year']
    final_df = pd.DataFrame(final_model_input, columns=feature_names)
    
    # 6. Prediction run karna
    prediction = model.predict(final_df)
    
    print(f"🚀 Prediction Result Successful!")
    print(f"Predicted IHSG Target Value: {prediction[0]:.3f}")

except Exception as e:
    print("❌ Error: Pipeline execution fail ho gayi!")
    print(f"Technical Error Details: {str(e)}")

--- ML Components Loading Test ---
✅ Success: Saari `.pkl` files perfectly load ho gayi hain!
Trained Columns List: ['OIL', 'GOLD', 'USDIDR', 'SP500', 'VIX', 'CPI', 'BI_rate', 'US_rate', 'year']

--- Pipeline Execution Test ---
🚀 Prediction Result Successful!
Predicted IHSG Target Value: 2774.708

C:\Users\Amir sohail\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [22]:
import sklearn
sklearn.__version__

'1.7.2'